#!/bin/bash

echo "--- :checkered_flag: Running pre-command"

echo "About to run npm ci"

docker run --rm \
  -v $PWD:/app \
  -v $HOME/.npmrc:/root/.npmrc \
  -w /app \
  278521702583.dkr.ecr.us-west-2.amazonaws.com/arch/node-v20-builder:v2.0.2 \
  bash -c 'npm ci --no-audit'
