<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { toastService } from '@siteminder/sui-core/services'
import { useTranslate } from '@/composables/use-translate'
import { User, useUserManagement } from '@/composables/use-user-management'

/**
 * IMPORTANT
 *
 * This section will be used for training/onboarding purposes.
 * Please refrain from adding/updating any code unless it's for that purpose.
 */

const router = useRouter()

// Check add.lang.json file for the available strings
const { t } = useTranslate('views.users.add')

// These are mock data and function and won't persist any saved data
const { users, addUser } = useUserManagement()

// Mocked predefined options for the select, feel free to test with different values
const languages = ref([
  {
    label: 'English',
    code: 'en',
  },
  {
    label: 'French',
    code: 'fr',
  },
  {
    label: 'German',
    code: 'de',
  },
])

// Mocked predefined options for the select, feel free to test with different values
const userRoleOptions = ref([
  {
    label: 'General',
    code: 'general',
  },
  {
    label: 'Admin',
    code: 'admin',
  },
])

const userForm = ref<User>({
  id: `${users.value.length + 1}`, // Mock id, generally it should be generated by the backend
  // ANSWER: Fill in the remaining form values
  firstName: '',
  lastName: '',
  email: '',
  preferredLanguage: '',
  role: 'general',
  phoneNumber: undefined,
})

const isFormSaving = ref(false)

const createUser = async (): Promise<void> => {
  // For good UX, we show visual feedback to the user that the form is saving
  isFormSaving.value = true

  await addUser(userForm.value)

  // ANSWER: Show success message
  // - Use translatable string from add.lang.json
  toastService({
    type: 'success',
    title: t('create-user-toast-success-title'),
    message: t('create-user-toast-success-message'),
  })

  // ANSWER: Redirect to users/manage page
  await router.push({
    name: 'users/manage',
  })
}

const cancel = async (): Promise<void> => {
  await router.push({
    name: 'users/manage',
  })
}

const onInvalidForm = (): void => {
  // ANSWER: Show warning message
  // - Use translatable string from add.lang.json
  toastService({
    type: 'warning',
    title: t('create-user-toast-warning-title'),
    message: t('create-user-toast-warning-message'),
  })
}
</script>

<template>
  <sm-section>
    <sm-container :full-width="true">
      <sm-page-title :title="t('page-title')" />

      <!--
        ANSWER: Fill in missing parts of the form
        - Disable the form when saving
        - Handle @submit and call createUser function
        - Handle @invalid-submit and call onInvalidForm function
      -->
      <sm-form
        class="cm-max-w-lg"
        :disabled="isFormSaving"
        @invalid-submit="onInvalidForm"
        @submit="createUser"
      >
        <sm-form-group :legend="t('user-details-group-legend')">
          <!--
            ANSWER: Add email type input
            - Validation rules: Required and validates invalid email
            - Use translatable label `t('email-address-label')`
          -->
          <sm-input
            v-model="userForm.email"
            name="email"
            type="email"
            rules="required|email"
            :label="t('email-address-label')"
          />

          <!--
            ANSWER: Add first name type text input
            - Validation rules: Required
            - Use translatable label `t('first-name-label')`
          -->
          <sm-input
            v-model="userForm.firstName"
            name="first-name"
            rules="required"
            :label="t('first-name-label')"
          />

          <!--
            ANSWER: Add last name type text input
            - Validation rules: Required
            - Use translatable label `t('last-name-label')`
          -->
          <sm-input
            v-model="userForm.lastName"
            name="last-name"
            rules="required"
            :label="t('last-name-label')"
          />

          <!--
            ANSWER: Add preferred language select box
            - Mode: single selection
            - Validation rules: Required
            - Use translatable label `t('preferred-language-label')`
            - Use translatable placeholder `t('preferred-language-placeholder')`
          -->
          <sm-select
            v-model="userForm.preferredLanguage"
            rules="required"
            name="preferred-language"
            :label="t('preferred-language-label')"
            :options="languages"
            :placeholder="t('preferred-language-placeholder')"
          />

          <!--
            ANSWER: Add phone number type text input
            - Validation rules: None
            - Use translatable label `t('phone-number-label')`
          -->
          <sm-input
            v-model="userForm.phoneNumber"
            name="phone-number"
            :label="t('phone-number-label')"
          />
        </sm-form-group>

        <sm-divider margin-bottom="48px" />

        <sm-form-group :legend="t('platform-permissions-group-legend')">
          <!--
            ANSWER: Add user role select box
            - Mode: single selection with pre-selected value
            - Validation rules: Required
            - Use translatable label `t('user-role-label')`
          -->
          <sm-select
            v-model="userForm.role"
            rules="required"
            name="role"
            :label="t('user-role-label')"
            :options="userRoleOptions"
            :placeholder="t('user-role-placeholder')"
          />
        </sm-form-group>

        <div class="cm-flex cm-flex-row-end cm-mb-32 cm-mt-32">
          <!--
            ANSWER: Add tertiary cancel button
            - Disabled when saving
            - Use translatable button text `t('cancel-button')`
            - Call cancel function on click
          -->
          <sm-button
            type="tertiary"
            :disabled="isFormSaving"
            @click="cancel"
          >
            {{ t('cancel-button') }}
          </sm-button>

          <!--
            ANSWER: Add primary submit button
            - Disabled when saving
            - Loading state when saving
            - Use translatable button text `t('create-user-button')`
            - Set native type to submit which will trigger sm-form's event automatically
          -->
          <sm-button
            native-type="submit"
            type="primary"
            :loading="isFormSaving"
            :disabled="isFormSaving"
          >
            {{ t('create-user-button') }}
          </sm-button>
        </div>
      </sm-form>
    </sm-container>
  </sm-section>
</template>
